databases:
  - name: Elysian Table
    plan: free
    databaseName: elysian_table
    user: mysite

services:
  - type: web
    plan: free
    name: ElysianTable
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn elysian.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Elysian Table
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
