# Generated by Django 5.0.6 on 2024-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=46777777777, max_length=15),
            preserve_default=False,
        ),
    ]
